##########################################
#
# Sparkswap Broker-CLI and Broker-Daemon
# https://sparkswap.com
#
# Troubleshooting GRPC:
# - GRPC_VERBOSITY=INFO
# - GRPC_TRACE=all
#
##########################################

version: "2.4"

services:
  lnd_ltc:
    depends_on:
      - litecoind
    environment:
      - RPC_HOST=litecoind
      - ZMQPUBRAWBLOCK=tcp://litecoind:28333
      - ZMQPUBRAWTX=tcp://litecoind:28334
      - RPC_USER=${LTC_RPC_USER:?LTC_RPC_USER is required}
      - RPC_PASS=${LTC_RPC_PASS:?LTC_RPC_PASS is required}
      - RPC_HOST=${LTC_RPC_HOST:-}
      - NETWORK=${NETWORK}
      - DEBUG=info
      - EXTERNAL_ADDRESS="${EXTERNAL_LTC_ADDRESS}:10114"
      - EXTPREIMAGE_HOST=sparkswapd:40369
    image: sparkswap/lnd_ltc:0.4.1-beta
    ports:
      - "10114:9735"
    volumes:
      - "${DATA_DIR:?DATA_DIR is required}/lnd_ltc/shared:/shared"
      - "${DATA_DIR:?DATA_DIR is required}/lnd_ltc/data:/data"
    networks:
      - broker
    logging:
      options:
        max-size: 50m

  litecoind:
    image: sparkswap/litecoind:0.4.1-beta
    volumes:
      - ${DATA_DIR:?DATA_DIR is required}/shared:/shared
      - ${DATA_DIR:?DATA_DIR is required}/litecoin:/data
    environment:
      - RPC_USER=${LTC_RPC_USER}
      - RPC_PASS=${LTC_RPC_PASS}
      - NETWORK=${NETWORK}
      - DEBUG=info
      - DATA_DIR=/data # This should not be changed. This is passed into litecoind and is in context of the container.
      - RPC_LISTEN=0.0.0.0
    networks:
      - broker
    logging:
      options:
        max-size: 50m

volumes:
  shared:
  litecoin:
  lnd_ltc:

networks:
  broker:
