##########################################
#
# Sparkswap Broker-CLI and Broker-Daemon
# https://sparkswap.com
#
# Troubleshooting GRPC:
# - GRPC_VERBOSITY=INFO
# - GRPC_TRACE=all
#
##########################################

version: "2.4"

services:
  sparkswapd:
    image: sparkswap/broker:0.5.2-beta
    depends_on:
      - lnd_btc
      - lnd_ltc
    volumes:
      # block order and other sparkswap storage
      - "${DATA_DIR:?DATA_DIR is required}/sparkswap/data:/data"
      # This is populated externally w/ an engine
      - "${DATA_DIR:?DATA_DIR is required}/sparkswap/shared:/shared"
      # Persistent certs/keys for broker
      - "${SECURE_PATH}:/secure"
    environment:
      - NODE_ENV=production
      # - DATA_DIR=${DATA_DIR:-}
      - NETWORK=${NETWORK}
      - RPC_ADDRESS=${RPC_ADDRESS:-}
      - RPC_HTTP_PROXY_ADDRESS=${RPC_HTTP_PROXY_ADDRESS:-}
      - RPC_USER=${RPC_USER}
      - RPC_PASS=${RPC_PASS}
      - RPC_PUB_KEY=${RPC_PUB_KEY:-}
      - RPC_PRIV_KEY=${RPC_PRIV_KEY:-}
      - ID_PRIV_KEY=${ID_PRIV_KEY:-}
      - ID_PUB_KEY=${ID_PUB_KEY:-}
      - RELAYER_RPC_HOST=${RELAYER_RPC_HOST}
      - RELAYER_CERT_PATH=${RELAYER_CERT_PATH:-}
    ports:
      - "27492:27492"
      - "27592:27592"
    networks:
      - broker
    working_dir: "/home/app"
