##########################################
#
# sparkswap Broker-CLI and Broker-Daemon
# https://sparkswap.com
#
# Troubleshooting GRPC:
# - GRPC_VERBOSITY=INFO
# - GRPC_TRACE=all
#
##########################################

version: "2.4"

services:
  bitcoind:
    image: sparkswap/bitcoind:0.4.1-beta
    volumes:
      - ${DATA_DIR:?DATA_DIR is required}/sparkswap/shared:/shared
      - ${DATA_DIR:?DATA_DIR is required}/bitcoin:/data
    environment:
      - RPC_USER=${BTC_RPC_USER}
      - RPC_PASS=${BTC_RPC_PASS}
      - NETWORK=${NETWORK}
      - DEBUG=info
      - DATA_DIR=/data
      - RPC_LISTEN=0.0.0.0
    networks:
      - broker
    logging:
      options:
        max-size: 50m

  lnd_btc:
    image: sparkswap/lnd_btc:0.4.1-beta
    ports:
      - "10113:9735"
    environment:
      - RPC_HOST=${BTC_RPC_HOST:-bitcoind}
      - RPC_USER=${BTC_RPC_USER}
      - RPC_PASS=${BTC_RPC_PASS}
      - NETWORK=${NETWORK}
      - DEBUG=info
      - EXTERNAL_ADDRESS="${EXTERNAL_BTC_ADDRESS}:10113"
      - EXTPREIMAGE_HOST=sparkswapd:40369
      - ZMQPUBRAWBLOCK=${BTC_ZMQPUBRAWBLOCK:-}
      - ZMQPUBRAWTX=${BTC_ZMQPUBRAWTX:-}
      - ZMQPUBRAWBLOCK=tcp://bitcoind:28333
      - ZMQPUBRAWTX=tcp://bitcoind:28334
    volumes:
      - "${DATA_DIR:?DATA_DIR is required}/sparkswap/shared:/shared"
      - "${DATA_DIR:?DATA_DIR is required}/lnd_btc:/data"
    networks:
      - broker
    logging:
      options:
        max-size: 50m
    depends_on:
      - bitcoind

volumes:
  shared:
  bitcoin:

networks:
  broker:
